#!/usr/bin/env python

import subprocess
import sys
from xml.etree import ElementTree


def get_vm_harddrives(vmname):
    vmxml_str = subprocess.check_output(['virsh', 'dumpxml', vmname])
    vmxml = ElementTree.fromstring(vmxml_str)
    # Extract virtual hard drives list (excluding CD-ROMs) from libvirt XML
    #
    # <devices>
    #   <disk type='file' device='disk'>
    #     <driver name='qemu' type='raw'/>
    #     <source dev='/dev/wdgreen/saceph-mon-os'/>
    #  </disk>
    disks_xml = vmxml.findall("devices/disk[@device='disk']")
    # Get the backing (host) device from the virtual HD description
    #     <source dev='/dev/wdgreen/saceph-mon-os'/>

    def get_host_bdev_or_file(dxml):
        # <source dev='/dev/wdgreen/saceph-mon-os'/>
        # <source file='/srv/libvirt/images/saceph-mon-os.qcow2'/>
        # <source pool='foo' volume='bar'/>
        src_xml = dxml.findall('source')[0]
        pool = src_xml.get('pool')
        volume = src_xml.get('volume')
        if pool:
            hfile = subprocess.check_output(['virsh', 'vol-path',
                                             '--pool', pool, volume]).strip()
        else:
            hfile = src_xml.get('dev') or src_xml.get('file')
        return hfile

    return [get_host_bdev_or_file(dxml) for dxml in disks_xml]


def main():
    if len(sys.argv) != 2:
        print("Usage: get-vm-harddrives <VM-name>")
        sys.exit(1)
    vmname = sys.argv[1]
    host_devices = get_vm_harddrives(vmname)
    print('\n'.join(host_devices))
    sys.exit(0)


if __name__ == '__main__':
    main()
