#!/bin/sh
set -e
vm_name="$1"

MYSELF="${0##*/}"
if [ -z "$vm_name" ]; then
	echo "*** $MYNAME: Error: no vm name has been specified" >&2
	exit 1
fi

cd "${0%/*}"
build_dir=".build/config-drive/$vm_name"
./gen-cloud-conf.sh $vm_name

exec genisoimage -output "${vm_name}-config.iso" \
	-input-charset utf-8 \
	-volid config-2 \
	-joliet -rock \
	"${build_dir}"
